services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: hivelord
      POSTGRES_PASSWORD: hivehivehive
      POSTGRES_DB: hive_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://hivelord:hivehivehive@db:5432/hive_db
      VIDEOS_DIR: /mnt/data/dataset/lsfb/videos
      EXTRACTED_DIR: /mnt/data/dataset/lsfb/extracted
      ZIP_OUTPUT_DIR: /mnt/data/dataset/lsfb/processing_result
      SERVER_URL: http://34.118.102.249:8000
    volumes:
      - /mnt/data/dataset/lsfb/videos:/data/videos:ro
      - /mnt/data/dataset/lsfb/extracted:/data/extracted
      - /mnt/data/dataset/lsfb/processing_result:/data/processing_result
    ports:
      - "8000:8000"

volumes:
  postgres_data: