services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: hivelord
      POSTGRES_PASSWORD: hivehivehive
      POSTGRES_DB: hive_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://hivelord:hivehivehive@db:5432/hive_db
      VIDEOS_DIR: /data/videos
      EXTRACTED_DIR: /data/extracted
      ZIP_OUTPUT_DIR: /data/processing_result
      SERVER_URL: https://hiveprocess.duckdns.org
    volumes:
      - /mnt/data/dataset/lsfb/videos:/data/videos:ro
      - /mnt/data/dataset/lsfb/extracted:/data/extracted
      - /mnt/data/dataset/lsfb/processing_result:/data/processing_result
    expose:
      - "8000"

  caddy:
    image: caddy:2
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  caddy_data:
  caddy_config: