training:
  epochs: 40
  batch_size: 8
  learning_rate: 0.0004
  weight_decay: 0.0001
  grad_clip: 1.0
  kl_weight: 0.5
  lm_model: "4gram.arpa"
  lexicon: "lexicon.txt"
  mirror_data: false

model:
  dropout: 0.2

data:
  dataset: "pjm"  # "phoenix" or "pjm"
  train_dir: "pjm_dataset"
  dev_dir: "pjm_dataset"
  test_dir: "pjm_dataset"
  annotation_dir: "annotations/pjm_json"
  train_ann: "annotations/PJM.train.txt"
  dev_ann: "annotations/PJM.test.txt"
  test_ann: "annotations/PJM.test.txt"
  num_workers: 8
  pin_memory: true

optimizer:
  milestones: [20, 35]
  gamma: 0.1

system:
  checkpoint_dir: "checkpoints"
  device: "auto"

logging:
  tensorboard: true
  wandb: false
  log_interval: 100
  histogram_interval: 100
  gradient_interval: 100
  log_dir: "runs"
