name: Formatting Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check formatting
        run: uvx ruff format --check .

      - name: Check norms and docstrings
        run: uvx ruff check .

      - name: Type checking
        run: uv run mypy .
